# Ledger: YTS Financial Report  

This notebook shows the YE Financial Report for the year of the LLC

<u>Table Of Contents</u>

## 1. Income Statement (Profit & Loss) 
- This report, typically attached to the 1065 as a supporting schedule, shows the revenue and expenses for the tax year.
## 2. Balance Sheet

In [1]:
# Load bookkeeping services
import os
from ledger.LLC import LLC
from pathlib import Path
import datetime
import pandas as pd
import numpy as np
from IPython.display import display, Markdown

strAmt = lambda n : f"${n:,.0f}"

# Top of LLC file directory
top = Path.cwd().parents[2]
llc = LLC('WBGroupLLC',debug=False, top=top)  # debug='details'
_ = llc._Bank()

In [ ]:
from stmt.stmtFinancialReport import stmtFinancialReport

fr = stmtFinancialReport(llc)
#fr.display()

AI query: as a expert tax preparer for a multi member LLC  who purchased a house that is in service and being leased and purchased a second property that is under construction -  give me am example of a single YE Financial Report to turn in with form 1065

In [3]:
llc.bk.df.head(2)

,dt,amt,C2,CheckNo,desc,TransType,Acct,AcctSub,TDesc
0,2025.12.29,-177.0,*,NaN,Cash eWithdrawal in Branch 12/29/2025 13:47 PM...,Exp,Acct.Fixed.Tangible.InService,NaN,Property Purchase
1,2025.12.29,177.0,*,NaN,eDeposit in Branch 12/29/25 03:48:15 PM 14650 ...,Rev,Acct.Cash.Bank,NaN,Owner Investment

In [4]:
#fr.bsDF
from IPython.display import display

bkDF = llc.bk.df.copy()

# Load Asset transactions
aObj = llc.assets()
aDF = aObj.assetsAcct().copy()
aDF.amt = aDF.bal

# Create Bank Unique Identifier
bkDF['dt'] = pd.to_datetime(bkDF.dt).apply(lambda d : d.strftime('%Y.%m.%d'))
#display(bkDF.head(3))
#display(aDF.head(3))
def join(self, aDF, bDF, key='kID', ):
    aDF.index = aDF.apply(lambda r: self._key(r)[0],axis=1)
    if len(aDF.index.unique()) != len(aDF) :
        print("ERROR: DF Join: DF1 keys are not unique, continuing")

    bDF.index = bDF.apply(lambda r: self._key(r)[0],axis=1)
    if len(bDF.index.unique()) != len(bDF) :
        print("ERROR: DF Join: DF2 keys are not unique, continuing")

    return aDF.join(bDF, how='outer', rsuffix=f"_{self.oID}")
    
glDF = join(aObj, bkDF, aDF)
glDF

,dt,amt,C2,CheckNo,desc,TransType,Acct,AcctSub,TDesc,dt_llcAssets,...,propID,propAddr,propOwners,tID,tDB,refDB,refDoc,_unknown,AL,bal
2025.08.20_-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025.08.20,...,a20250820-Cash1,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250820-Cash1,llcAssets,llcBank,Cash_LLC:llcBank Stmt,{},Equity,-0.0
2025.08.20_-219000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025.08.20,...,e20250826-805HMD,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250826-Cash1,llcAssets,llcAssets,H_805HighMesa: Closing Docs 2025.08.26,{},Equity,-219000.0
2025.08.20_-50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025.08.20,...,e20250826-805HMD,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250826-Cash2,llcAssets,llcAssets,H_805HighMesa: Closing Docs 2025.08.26,{},Equity,-50.0
2025.08.20_219000.0,2025.08.20,219000.00,*,NaN,WT FED#02M03 NATIONAL FINANCIAL /ORG=FRANCIS X...,Rev,Acct.Cash.Bank,NaN,Owner investment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025.08.20_50.0,2025.08.20,50.00,*,NaN,WFB OPENING DEPOSIT FROM CARD XXXXXXXXXXXX1980...,Rev,Acct.Cash.Bank,NaN,Owner Investment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025.12.10_-129.16,2025.12.10,-129.16,*,NaN,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,Exp,Acct.Exp.Util,Elec,Pay Monthly Util,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025.12.18_-50.0,2025.12.18,-50.00,*,NaN,BILL PAY Water-COMWSC RECURRING 38 ON 12-18,Exp,Acct.Exp.Util,Water,Pay Monthly Util,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025.12.26_-135.8,2025.12.26,-135.80,*,NaN,ALLSTATE IND CO INS PYMT DEC024 00000043853221...,Exp,Acct.Exp.Util,Ins_Home,Pay Monthly Util,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025.12.29_-177.0,2025.12.29,-177.00,*,NaN,Cash eWithdrawal in Branch 12/29/2025 13:47 PM...,Exp,Acct.Fixed.Tangible.InService,NaN,Property Purchase,2025.12.29,...,e20251229-RV1,Mobile,{'LLC': 100},e20251229-RV1,llcAssets,llcAssets,RV_RV1: Bill of Sales,{},Equity,-177.0
2025.12.29_177.0,2025.12.29,177.00,*,NaN,eDeposit in Branch 12/29/25 03:48:15 PM 14650 ...,Rev,Acct.Cash.Bank,NaN,Owner Investment,2025.12.29,...,e20251229-RV1,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20251229-Cash1,llcAssets,llcAssets,RV_RV1: Bill of Sales,{},Asset,177.0

In [5]:
glDF.columns

Index(['dt', 'amt', 'C2', 'CheckNo', 'desc', 'TransType', 'Acct', 'AcctSub',
       'TDesc', 'dt_llcAssets', 'desc_llcAssets', 'amt_llcAssets', 'aType',
       'acct', 'Ledger', 'acctMajor', 'acctMinor', 'acctSub', 'propNm',
       'propID', 'propAddr', 'propOwners', 'tID', 'tDB', 'refDB', 'refDoc',
       '_unknown', 'AL', 'bal'],
      dtype='object')

In [6]:
c = ['oID', 'addr', 'amt', 'dt', 'stakeholderPct', 'acct', 'aType', 'propNm',
       'propRef', 'desc', 'Ledger', 'kwList', 'amtType', 'basis',
       'improvements', 'pct']
g = aDF.groupby(['propNm', 'acct']).bal.sum()
gSub = aDF.groupby(['propNm']).bal.sum()
pList = list(df_sub.index)
xDF = pd.DataFrame()
for pNm in pList:
    sRow = pd.DataFrame([dict(propNm=pNm, acct=f'----- SubTotal {pNm}', bal=gSub.loc[pNm])])
    xDF = pd.concat([xDF, aDF[(aDF.propNm == pNm) & (aDF.aType=='Debit')][['propNm', 'Ledger', 'bal']],sRow])
xDF.bal = xDF.bal.astype(int)
xDF

NameError: name 'df_sub' is not defined

In [ ]:
import pandas as pd
import numpy as np

# Example DataFrame
data = {'State': ['CA', 'WA', 'AZ', 'CA', 'WA', 'AZ'],
        'Sales': [100, 200, 150, 120, 180, 160]}
df = pd.DataFrame(data)

# 1. Calculate subtotals for each State
df_s = df.groupby('State')['Sales'].sum().reset_index()
df_s['State'] = df_subtotal['State'] + ' Total' # Label the subtotal rows

# 2. Calculate grand total
df_grand_total = pd.DataFrame({'State': ['Grand Total'], 'Sales': [df['Sales'].sum()]})

# 3. Combine original, subtotals, and grand total
# Use pd.concat to stack them, then sort
combined_df = pd.concat([df, df_s, df_grand_total], ignore_index=True)
combined_df = combined_df.sort_values('State')#.reset_index(drop=True)

df_s

In [4]:
# IRS Guide
#display(Markdown(stmtFinancialReport(llc).mdIRS()))

In [ ]:
from ledger.stmtCashFlowStmt import stmtCashFlow
stmtCashFlow(fr).displayCashFlow()

### Expenses
- Advertising: $5,000
- Contract Labor: $10,000
- Depreciation: $2,000
- Office Expenses: $1,500
- Rent: $12,000
- Salaries & Wages: $30,000
- Utilities: $2,500
- Total Expenses: $63,000

In [ ]:
from ledger.llcExpenses import llcExpenses

exp = llcExpenses(llc)
exp.mdIRS()

In [ ]:
def frExpenses(self):
    # Summary of all Acct in GL
    glAcctDF = self._getAccts()

    _Acct = 'Acct.Cash.Income'

    # List of accounts
    aList = [dict(Account='Gross Receipts/Sales', amt=glAcctDF.loc[revAcct], Acct='revAcct'),
             dict(Account='', amt=0, Acct=np.nan),
             dict(Account='', amt=0, Acct='np.nan')
            ]
    return _buildGL(self, aList)

df3 = llc.bk.df
df3 = df3[df3.TransType == 'Exp']
eDF = pd.DataFrame(df3.groupby(['Acct','AcctSub']).amt.sum())
eDF

In [ ]:
# Load bookkeeping services
import os
from ledger.LLC import LLC
from pathlib import Path
import datetime
import pandas as pd
from IPython.display import display, Markdown

top = os.path.join(Path.home(, 'GDrive/Family/Assets-Hobby/RealEstateInvestments/LLC-WB-Group')
llc = LLC('WBGroupLLC',debug=False, top=top)  # debug='details'
llc._Bank()

begBal = llc._assets()._BegBal()

dtReport = datetime.datetime.now().strftime('%Y.%m.%d')
s =  f"### Financial Report - {dtReport}\n"
s += f"- **LLC Name: {llc.objName}**\n"
s += f"- **Year: {llc.yr}**\n"
s += f"- **Beginning Balance** (Acct.Equity.Cash):  {begBal}"

display(Markdown(s))

## General Ledger Account Summary

In [ ]:
# General Ledger - All accounts
llc._Bank()
glDF = llc.bk.df.groupby(['Acct']).amt.sum()
glDF.loc[f'Balance'] = glDF.sum()
print(glDF.to_string())

## Profit(Loss) Statement (P&L): 
- revenue, expenses, and net profit over the fiscal year to determine profitability.

In [ ]:
# Profit/Loss reconcile with Bank Stmt Balance
df = llc.bk.df.copy()
def _isProfitLoss(self, r):
    if 'Equity' in r.Acct : return 'Equity'
    if r.TransType == 'Exp' : return 'Expense'
    return 'Revenue'

# Classify Transactions into Exp, Rev or False (something else)
df['PnL'] = df.apply(lambda r: _isProfitLoss(llc, r, axis=1)

# Filter only Exp/Rev
plDF = pd.DataFrame(df[df.PnL != 'Equity'])

# Build table subcategories: P&L, Acct and ammount
pvt = pd.pivot_table(plDF, values='amt', index=['PnL', 'Acct'], aggfunc='sum')
pvt.loc[('Total','Profit(Loss)'),'amt'] = round(pvt.amt.sum(),2)
pvt

## Balance Sheet: 
Provides a snapshot of assets, liabilities

In [ ]:
df = llc. bk.df
eDF = df[df.Acct.str.contains('Equity')]
eDF.groupby('Acct')['amt'].sum()

## Equity Ledger
- members equity at year-end, ensuring the equation

## Cash Flow Statement:
Tracks actual cash inflows and outflows for the year, focusing on liquidity.

## General Ledger Details
- documenting every transaction categorized by account, 
- `detailed breakdown` often used for auditing or investigating
- specific transaction data supporting the financial statements.

## Revenue Ledger

## Expenses Ledger

## Assets Ledger

## Liabilities

## Equity Ledger

## Investment Ledger
- shows investments (cash/property/others) in year
- AcctSub identifies investment owners (o#) or Asset Values Purchases (p#)
- YE Gain/Losses shows profit of $1606.13

In [ ]:
# Investment Ledger
import pandas as pd
iDF = llc.bk.df[llc.bk.df.Acct.str.contains('Investment')].copy()
iDF = pd.concat([iDF, llc.bk.df[llc.bk.df.Acct.str.contains('Purchase')].copy()])
#iDF = pd.DataFrame(iDF.groupby(['AcctSub','Acct']).amt.sum())
iDF = iDF[['Acct', 'dt', 'amt', 'TDesc', 'AcctSub']].reset_index(drop=True).copy()
iDF.set_index('Acct', drop=True, inplace=True)

# Compute balance : investment/purchases and bank
baliDF = round(iDF.amt.sum(),2)
balBk = round(float(llc.bk.df.amt.sum(),2)

iDF.loc['NetValue YE'] = ['12/31/2025',baliDF,'YE Balance','']
iDF.loc['Gain/Loss YE'] = ['12/31/2025',balBk-baliDF,'Income/Expenses','']
iDF.loc['Acct.Cash.Balance'] = ['12/31/2025',balBk,'YE Cash Balance','']

display(iDF)

# Ledger - Income

In [ ]:
# Investment Ledger
incDF = llc.bk.df[llc.bk.df.Acct.str.contains('.Income')].copy()
incDF = pd.DataFrame(incDF.groupby(['Acct','AcctSub','dt']).amt.sum())

# --- lookup customer name based on ID
cList = llc.customers()
custList = []
for (acct, ndx,dt) in incDF.index:
    for d in cList:
        if d['oID'] == ndx: custList.append(d['nm'])
        else: custList.append('na')
incDF['Customer'] = custList
incDF.loc[('Total','','')] = [incDF.amt.sum(),'']
incDF

## Ledger - Profit/Loss

#### Expenses: YE Summary per Account

In [ ]:
# Subtotal Expenses
expDF = pd.DataFrame(plDF[plDF.PnL == 'Expense'][['Acct','amt']].groupby('Acct').amt.sum())
balExp = round(expDF.amt.sum(),2)
expDF.loc['Subtotal'] = balExp
display(expDF)

#### Revenue: : YE Summary per Account

In [ ]:
# Subtotal Expenses
revDF = pd.DataFrame(plDF[plDF.PnL == 'Revenue'][['Acct','amt']].groupby('Acct').amt.sum())
balRev = round(revDF.amt.sum(),2)
revDF.loc['Subtotal'] = balRev
display(revDF)

### Gain/Loss: YE Summary

In [ ]:
# YE Summary
pd.DataFrame([['Expense', 'Gains', 'Total Operating Gain/Loss'],
               [balExp, balRev, balRev+balExp]], index=['YE Summary','Amt']).transpose()

## Ledger - Expenses Details

In [ ]:
df3 = llc.bk.df
df3 = df3[df3.TransType == 'Exp']
pd.DataFrame(df3.groupby(['Acct','AcctSub']).amt.sum())

In [ ]:
# Investment Ledger
expDF = llc.bk.df[llc.bk.df.Acct.str.contains('Expense')].copy()
df2 = pd.DataFrame(expDF.groupby('AcctSub').amt.sum())
balExp = df2.sum()
df2.loc['Total'] = [balExp]
display(df2)
expDF[['dt', 'amt', 'Acct', 'AcctSub', 'TDesc']]

## Ledger - Misc Transaction Summary

In [ ]:
# Miscellenous / Unclassified Transactions
llc.bk.df[llc.bk.df.Acct.str.contains('Misc')][['dt', 'amt', 'AcctSub', 'desc']]

## Owner Details

In [ ]:
# Owners DB
pd.DataFrame(llc.owners())

## Customer Details

In [ ]:
# Customer DB
pd.DataFrame(llc.customers())

## Asset Details

In [ ]:
# Asset DB
from ledger.llcAssets import llcAssets

a = llcAssets(llc)
a.fetch()
a.df

# Accounting-Bookkeeping 101

## accounting ledgers: 

| Ledger | Description |
| :---- | :----: |
|General Ledger | master document; record all transactions; includes all accounts related to a company's assets, liabilities, equity, revenue, and expenses.|
|Sales Ledger | |
|Purchase Ledger |  

## Key Principles (pyApps)

- utilizing pythn accounting libraries
- double-entry bookkeeping, or by
- building a custom application (general ledger for rental LLC)
- a web framework / command-line tool
- read bank statements (often from CSV files)
- perform transactions and reporting. 

### Beancount: 
A Python package for double-entry accounting. You can use its command-line tools to manage financial transactions written in a plain-text file, making it suitable for tracking an LLC's finances and maintaining a Git-based audit trail.
### Blnk Finance: 
An open-source, developer-focused toolkit that includes a double-entry ledger for managing balances and transactions. It offers features like balance monitoring, reconciliation, and identity management, and is designed to help you build fintech products.
### Django Ledger: 
An open-source accounting and financial ledger system built on the Django framework. It's a good option if you need to integrate robust accounting features directly into a Python web application. 

### Github Py Ledgers

1. [**>Confidential Ledger Azure**](https://learn.microsoft.com/en-us/python/api/overview/azure/confidentialledger-readme?view=azure-python#key-concepts)
    - good reference
1. [**> Ledger Visualization**](https://wilw.dev/blog/2022/04/24/ledger-python-visualisation/) : pure text (csv) files, uses vis.py

## Ledger for Taxes

- bare minimum records
- accounting ledger for an LLC to file taxes
- clear, accurate summary
  - all business income (gross receipts)
  - expenses.
- no specific bookkeeping method
- method used must clearly reflect your income and expenses. 

## key information required for each transaction includes:

- Amount of the transaction.
- Date of the transaction.
- Description of the item purchased or service received.
- Business purpose (why the expense was necessary).
- Source of income or the payee for expenses. 
- Essential Records and Documentation

## Documentation
The IRS requires that you maintain documentation to support the figures reported on your tax return. 

- Well-organized,
- detailed records make tax preparation easier
- help you maximize deductions
- ensuring you have the necessary documentation in case of an IRS audit.
- Records: keep at least three years from the date you filed the return. 


|Record Type 	|Description	|Supporting Documents to Keep|
| ---- | ---- | ---- |
|Income	|All gross receipts from business operations.	|Invoices sent to clients, cash register tapes, deposit slips, bank account deposits, and Forms 1099-NEC received.
|Expenses	|All costs incurred to carry on your business.|	Canceled checks, credit card statements, invoices for purchases, and receipts.|
|Assets & Depreciation|	Records for property like equipment or vehicles used in the business that last more than a year.	|Date and method of acquisition, purchase price, cost of improvements, deductions taken for depreciation, business use, and details of disposition/sale.|
|Payroll (if applicable)|	Records related to employees (not owners, typically).|	Annual W-2s, quarterly and annual payroll tax returns, and complete pay records/time sheets for each employee.|

### Multi-member LLC: Filing Requirements by LLC Structure
- Your LLC's tax classification determines which forms you will need to file, which impacts how you report your income and expenses. 
- Multi-member LLC: The default is to be taxed as a partnership. The LLC files an informational Form 1065 and provides a Schedule K-1 to each member, who then reports their share of profit or loss on their personal Form 1040 using Schedule E.
- LLC taxed as a Corporation (S corp or C corp): If you elect this status, you will file Form 1120 (C corp) or Form 1120-S (S corp).

# Accounting: Best Practices

## Rental Accounting

|Account              |	Debit | Credit| Date | SubAcct | Description |
| ------------------- | :----- | :----: | :----- | :----: | :----- |
|Acct.Cash.Income     | ##.## |       | yy.mm.dd | CustID  | record the cash received |
|Acct.Rent.Receivable | ##.## |       | yy.mm.dd | CustID  | record amt owed by the tenant|
|Income.Rent.Revenue  |       | ##.## | yy.mm.dd | CustID  | record total income earned, period |

## Initial investment of cash
|Account              |	Debit | Credit| Date | SubAcct | Description |
| ------------------- | :----- | :----: | :----- | :----: | :----- |
|Acct.Cash.Investment |       | ##.## | yy.mm.dd |           | record cash investment|
|LLC.Equity.Member    | ##.## |       | yy.mm.dd | memberID  | LLC equity, member % |

## Company purchasing an investment
|Account              |	Debit | Credit| Date | SubAcct | Description |
| ------------------- | :----- | :----: | :----- | :----: | :----- |
|LLC.Prop.Investment  | ##.## |        | yy.mm.dd | propID | record value of purchase/investment|
|Acct.Cash.Purchase   |       | ##.##  | yy.mm.dd | propID | Cash account reduced |

## Expense: Paid by Cash / Debit Card
|Account              |	Debit | Credit| Date | SubAcct | Description |
| ------------------- | :----- | :----: | :----- | :----: | :----- |
|Acct.Cash.Expense    |       | ##.##  | yy.mm.dd | expCls | record expense details|
|Acct.Expense.<expCls>| ##.## |        | yy.mm.dd | expCls | record expense details|


## Expense: Paid by accured (credit card/loan-agreement/late payment)
|Account              |	Debit | Credit| Date | SubAcct | Description |
| ------------------- | :----- | :----: | :----- | :----: | :----- |
|Liab.Payable.Expense |       | ##.## | yy.mm.dd | expCls | record expense details |
|Liab.Expense.<expCls>| ##.## |       | yy.mm.dd | expCls | record expense details|
| | | | | | future |
|Acct.Cash.Expense    |       | ##.## | yy.mm.dd | expCls | record expense details|
|Acct.Expense.<expCls>| ##.## |       | yy.mm.dd | expCls | record expense details|


Example: Recording rent expense Transaction: A company pays \(\$1,000\) for monthly rent.Debit: The Rent Expense account is debited for \(\$1,000\).Credit: The Cash account is credited for \(\$1,000\). 

Note 3Example: Recording an accrued expense Transaction: At the end of the month, a company has an accrued electricity expense of \(\$300\) that has not yet been paid.Debit: The Electricity Expense account is debited for \(\$300\).Credit: The Accrued Expenses (or Electricity Expense Payable) account is credited for \(\$300\) to create the liability. 


## NOTE 1: Subsequent changes to the investment
- accounting for an investment becomes more complex, 
- value of investment fair value method or equity method,
- depending on the type of investment.

## NOTE 2: Earnings from investments
- recognized in the `income statement`
- dividends received are often treated as either operating or investment inflows
- `cash flow statement`.

## NOTE 3: accrual method
- expenses are recorded when they are incurred, not when they are paid.
- Example: Recording an accrued expense Transaction:
    - end of the month, not paid elect expense 
    - a company has an accrued electricity expense of $300
    - Debited $300 :  Expense.Utility.Elec
    - Credit $300 : Liab.Expense.Utility
    - The Accrued Expenses (or Electricity Expense Payable) - create the liability.
    - 
## NOTE 4: Investments on form 1065
- An LLC taxed as a partnership records owner investments (`capital contributions`) on IRS Form 1065,
- primarily on `Schedule L (Balance Sheets per Books)` and
- Schedule M-2 (Analysis of Partners' Capital Accounts).
- Investments are considered `capital contributions` rather than income
- Capital contributions are tracked to determine the partners' basis in the LLC