# llcAPI_test

## See ledger/llcAPI.py

In [1]:
# Load bookkeeping services
import os, sys
from pathlib import Path
if len([p for p in sys.path if 'Ledger' in p]) == 0:
    sys.path.append(os.path.join(os.getcwd(), 'Ledger'))

## TEST : Load profile

In [2]:
from ledger.LLC import LLC
import datetime
from IPython.display import display, Markdown

# Load LLC and its profile
top = os.path.join(Path.home(), 'GDrive/Family/Assets-Hobby/RealEstateInvestments/LLC-WB-Group')
llc = LLC('WBGroupLLC',debug=True, top=top)

# Summarize LLC
dtReport = datetime.datetime.now().strftime('%Y.%m.%d')
display(Markdown(f"### Profile - {dtReport}"))
display(Markdown(f"- **LLC Name: {llc.objName}**"))
display(Markdown(f"- **Year: {llc.yr}**"))

llc:LLC init load _Profile
LLC llcProfile FN /Users/frankrojas/GDrive/Family/Assets-Hobby/RealEstateInvestments/LLC-WB-Group/llcProfile_WBGroupLLC.json
Profile loaded /Users/frankrojas/GDrive/Family/Assets-Hobby/RealEstateInvestments/LLC-WB-Group/llcProfile_WBGroupLLC.json
llc:LLC LLC Init Done

### Profile - 2026.03.14

- **LLC Name: WBGroupLLC**

- **Year: 2025**

## Test: Load Bank csv

In [3]:
from ledger.llcBank import llcBank

bk = llcBank(llc, debug=True)
bk.fetch()

llcBank llcBank Init Done
llcBank llcBank Init Done
llcBank dwnLdCSV: importBankCSV csvBN: WBGroupLLC_WF_20251231.csv
llcBank CSV Loaded /Users/frankrojas/GDrive/Family/Assets-Hobby/RealEstateInvestments/LLC-WB-Group/pages/AccountingData/2025/BankStmts/WBGroupLLC_WF_20251231.csv
llcAssets llcAssets Init Done
llc:llcAssets llcAssets Init Done
llcAssets ledgerObject.FN: /Users/frankrojas/GDrive/Family/Assets-Hobby/RealEstateInvestments/LLC-WB-Group/pages/AccountingData/Accts/llcAssets_WBGroupLLC.json
llcAssets ledgerObject.FN: /Users/frankrojas/GDrive/Family/Assets-Hobby/RealEstateInvestments/LLC-WB-Group/pages/AccountingData/Accts/llcAssets_WBGroupLLC.json
ledgerClassify ledgerClassify Init Done

In [4]:
bk.df

,dt,amt,C2,CheckNo,desc,TransType,Acct,AcctSub,TDesc
0,12/29/2025,-177.00,*,NaN,Cash eWithdrawal in Branch 12/29/2025 13:47 PM...,Exp,Acct.Asset.Purchase,p20251229-RV1,Purchase Rental RV
1,12/29/2025,177.00,*,NaN,eDeposit in Branch 12/29/25 03:48:15 PM 14650 ...,Rev,Acct.Cash.Investment,o20250801_1,Initial Investment by member
2,12/26/2025,-135.80,*,NaN,ALLSTATE IND CO INS PYMT DEC024 00000043853221...,Exp,Acct.Cash.Util,Ins_Home,Pay Monthly Util
3,12/18/2025,-50.00,*,NaN,BILL PAY Water-COMWSC RECURRING 38 ON 12-18,Exp,Acct.Cash.Util,Water,Pay Monthly Util
4,12/10/2025,-129.16,*,NaN,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,Exp,Acct.Cash.Util,Elec,Pay Monthly Util
5,12/01/2025,1500.00,*,NaN,ZELLE FROM NICOLA ROJAS ON 12/01 REF # BBT3528...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
6,11/18/2025,-50.00,*,NaN,BILL PAY Water-COMWSC RECURRING 38 ON 11-18,Exp,Acct.Cash.Util,Water,Pay Monthly Util
7,11/17/2025,-2.00,*,NaN,PURCHASE AUTHORIZED ON 11/15 HAYS CO TX WIMBER...,Exp,Acct.Cash.Expense,hays,Expense: 11/15 hays co tx wimber fort worth tx...
8,11/17/2025,-30.00,*,NaN,PURCHASE AUTHORIZED ON 11/15 HAYS CO TX WIMBER...,Exp,Acct.Cash.Expense,hays,Expense: 11/15 hays co tx wimber san marcos tx...
9,11/17/2025,-19.47,*,NaN,PURCHASE AUTHORIZED ON 11/15 AMAZON MKTPL*B80W...,Exp,Acct.Cash.Expense,amazon,Expense: 11/15 amazon mktpl*b80w8 amzn.com/bil...
10,11/17/2025,-32.42,*,NaN,PURCHASE AUTHORIZED ON 11/14 SP GROWERS SOLUTI...,Exp,Acct.Cash.Expense,sp,Expense: 11/14 sp growers solutio growerssolut...
11,11/12/2025,1500.00,*,NaN,ZELLE FROM NICOLA ROJAS ON 11/11 REF # BBT3482...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
12,11/10/2025,-119.49,*,NaN,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,Exp,Acct.Cash.Util,Elec,Pay Monthly Util
13,11/07/2025,-42.15,*,NaN,PURCHASE AUTHORIZED ON 11/06 SP GROWERS SOLUTI...,Exp,Acct.Cash.Expense,sp,Expense: 11/06 sp growers solutio growerssolut...
14,11/03/2025,-73.56,*,NaN,PURCHASE AUTHORIZED ON 11/02 AMAZON MKTPL*NK5P...,Exp,Acct.Cash.Expense,amazon,Expense: 11/02 amazon mktpl*nk5ps amzn.com/bil...
15,11/03/2025,-487.13,*,NaN,PURCHASE AUTHORIZED ON 10/31 LAIRD PLASTICS SA...,Exp,Acct.Cash.Expense,laird,Expense: 10/31 laird plastics san 469-299-7029...
16,10/24/2025,-0.53,*,NaN,TRUIST ACCTVERIFY 251024 15280212831 ALEJANDRO...,Exp,Acct.Cash.Misc,Misc,Misc Expense
17,10/24/2025,0.29,*,NaN,TRUIST ACCTVERIFY 251024 15280212821 ALEJANDRO...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
18,10/24/2025,0.24,*,NaN,TRUIST ACCTVERIFY 251024 15280212827 ALEJANDRO...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
19,10/24/2025,400.00,*,NaN,Promotion Bonus,Rev,Acct.Interest.Income,Bank,Bank Promotion for account openning
20,10/23/2025,1000.00,*,NaN,ZELLE FROM ALEJANDRO VILLARREAL ON 10/23 REF #...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
21,10/22/2025,-135.00,*,NaN,VENMO ADDFUNDS 251022 1045679339909 FRANCIS ROJAS,Exp,Acct.Cash.Expense,Maintenance,"Repair Utility Outlet,Electrician"
22,10/22/2025,-36.09,*,NaN,PURCHASE AUTHORIZED ON 10/22 WIMBERLEY ACE WIM...,Exp,Acct.Cash.Expense,wimberley,Expense: 10/22 wimberley ace wimberley tx p000...
23,10/20/2025,-50.00,*,NaN,BILL PAY Water-COMWSC RECURRING 38 ON 10-20,Exp,Acct.Cash.Util,Water,Pay Monthly Util
24,10/17/2025,-57.31,*,NaN,PURCHASE AUTHORIZED ON 10/16 SQ *RODCO STEEL D...,Exp,Acct.Cash.Expense,sq,Expense: 10/16 sq *rodco steel di new braunfel...
25,10/16/2025,-60.58,*,NaN,PURCHASE AUTHORIZED ON 10/16 Harbor Freight To...,Exp,Acct.Cash.Expense,harbor,Expense: 10/16 harbor freight tools u san marc...
26,10/14/2025,-19.47,*,NaN,PURCHASE AUTHORIZED ON 10/13 AMAZON MKTPL*NM32...,Exp,Acct.Cash.Expense,amazon,Expense: 10/13 amazon mktpl*nm32n amzn.com/bil...
27,10/14/2025,-90.90,*,NaN,PURCHASE AUTHORIZED ON 10/13 TEXAS DISPOSAL SY...,Exp,Acct.Cash.Expense,texas,Expense: 10/13 texas disposal sys 800-3758375 ...
28,10/14/2025,-108.32,*,NaN,PURCHASE AUTHORIZED ON 10/12 H-E-B #708 WIMBER...,Exp,Acct.Cash.Expense,h-e-b,Expense: 10/12 h-e-b #708 wimberley tx s465285...
29,10/14/2025,-30.71,*,NaN,PURCHASE AUTHORIZED ON 10/10 WIMBERLEY ACE WIM...,Exp,Acct.Cash.Expense,wimberley,Expense: 10/10 wimberley ace wimberley tx s385...
30,10/10/2025,-72.50,*,NaN,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,Exp,Acct.Cash.Util,Elec,Pay Monthly Util
31,10/09/2025,-37.87,*,NaN,PURCHASE AUTHORIZED ON 10/08 WIMBERLEY ACE WIM...,Exp,Acct.Cash.Expense,wimberley,Expense: 10/08 wimberley ace wimberley tx s465...
32,10/09/2025,-14.06,*,NaN,PURCHASE AUTHORIZED ON 10/08 WIMBERLEY ACE WIM...,Exp,Acct.Cash.Expense,wimberley,Expense: 10/08 wimberley ace wimberley tx s585...
33,10/09/2025,14.06,*,NaN,PURCHASE RETURN AUTHORIZED ON 10/08 WIMBERLEY ...,Rev,Acct.Cash.Expense,wimberley,Expense: 10/08 wimberley ace wimberley tx s465...
34,10/08/2025,-34.63,*,NaN,PURCHASE AUTHORIZED ON 10/07 WIMBERLEY ACE WIM...,Exp,Acct.Cash.Expense,wimberley,Expense: 10/07 wimberley ace wimberley tx s585...
35,10/08/2025,-65.36,*,NaN,PURCHASE AUTHORIZED ON 10/07 H-E-B #708 WIMBER...,Exp,Acct.Cash.Expense,h-e-b,Expense: 10/07 h-e-b #708 wimberley tx s345280...
36,10/08/2025,-51.06,*,NaN,PURCHASE AUTHORIZED ON 10/07 WIMBERLEY ACE WIM...,Exp,Acct.Cash.Expense,wimberley,Expense: 10/07 wimberley ace wimberley tx s345...
37,10/08/2025,27.04,*,NaN,PURCHASE RETURN AUTHORIZED ON 10/07 LOWES #001...,Rev,Acct.Cash.Expense,lowes,Expense: 10/07 lowes #00159* san marcos tx s34...
38,10/07/2025,-50.00,*,102.0,CHECK # 102,Exp,Acct.Cash.Util,Util,Pay Electrician Repair Outlet
39,10/07/2025,-27.04,*,NaN,PURCHASE AUTHORIZED ON 10/07 LOWE'S #159 SAN M...,Exp,Acct.Cash.Expense,lowe's,Expense: 10/07 lowe's #159 san marcos tx p3052...
40,10/07/2025,-14.06,*,NaN,PURCHASE AUTHORIZED ON 10/07 WIMBERLEY ACE WIM...,Exp,Acct.Cash.Expense,wimberley,Expense: 10/07 wimberley ace wimberley tx p000...
41,10/07/2025,-31.86,*,NaN,PURCHASE AUTHORIZED ON 10/06 LOWES #00907* 866...,Exp,Acct.Cash.Expense,lowes,Expense: 10/06 lowes #00907* 866-483-7521 nc s...
42,10/06/2025,-140.73,*,NaN,PURCHASE AUTHORIZED ON 10/04 WAL-MART #0404 SA...,Exp,Acct.Cash.Expense,wal-mart,Expense: 10/04 wal-mart #0404 san marcos tx p0...
43,10/03/2025,-17.31,*,NaN,PURCHASE AUTHORIZED ON 10/03 WIMBERLEY ACE WIM...,Exp,Acct.Cash.Expense,wimberley,Expense: 10/03 wimberley ace wimberley tx p000...
44,10/03/2025,-8.29,*,NaN,PURCHASE AUTHORIZED ON 10/01 AMAZON MKTPL*NJ7X...,Exp,Acct.Cash.Expense,amazon,Expense: 10/01 amazon mktpl*nj7xx amzn.com/bil...
45,09/29/2025,30.00,*,NaN,MOBILE DEPOSIT : REF NUMBER :409290718471,Rev,Acct.Cash.Misc,Misc,Misc Income
46,09/22/2025,-38.94,*,NaN,PURCHASE AUTHORIZED ON 09/19 AMAZON MKTPL*B108...,Exp,Acct.Cash.Expense,amazon,Expense: 09/19 amazon mktpl*b108s amzn.com/bil...
47,09/10/2025,-25.94,*,NaN,PURCHASE AUTHORIZED ON 09/10 Kings Feed And Ha...,Exp,Acct.Cash.Expense,kings,Expense: 09/10 kings feed and hardware wimberl...
48,09/03/2025,-150.00,*,101.0,CHECK # 101,Exp,Acct.Cash.Util,Water,Pay Monthly Util
49,08/28/2025,-250.00,*,NaN,Pedernales Elect TEL PMTS 082825 1SNKYQ W B GR...,Exp,Acct.Cash.Util,Elec,Pay Monthly Util
50,08/28/2025,-75.76,*,NaN,PURCHASE AUTHORIZED ON 08/27 AMAZON MKTPL*6Y5U...,Exp,Acct.Cash.Expense,amazon,Expense: 08/27 amazon mktpl*6y5uj amzn.com/bil...
51,08/26/2025,-213936.95,*,NaN,WITHDRAWAL MADE IN A BRANCH/STORE,Exp,Acct.Asset.Purchase,p20250826-805HMD,Purchase Property: 805 High Mesa
52,08/20/2025,50.00,*,NaN,WFB OPENING DEPOSIT FROM CARD XXXXXXXXXXXX1980...,Rev,Acct.Cash.Investment,o20250801_1,Open Bank Acct Investment
53,08/20/2025,219000.00,*,NaN,WT FED#02M03 NATIONAL FINANCIAL /ORG=FRANCIS X...,Rev,Acct.Cash.Investment,o20250801_1,Initial Investment by member

## Test: Tranaction Classification

In [6]:
from ledger.llcAssets import llcAssets           
a = llcAssets(llc)
a.fetch()
r = bk.df.iloc[0]
a._matchBk(r)

s  = bk.df.apply(lambda r : a._matchBk(r), axis=1)
[r for r in s if r is not None]

[('Acct.Asset.Purchase', 'p20251229-RV1', 'Purchase Rental RV'),
 ('Acct.Cash.Investment', 'o20250801_1', 'Initial Investment by member'),
 ('Acct.Asset.Purchase',
  'p20250826-805HMD',
  'Purchase Property: 805 High Mesa'),
 ('Acct.Cash.Investment', 'o20250801_1', 'Open Bank Acct Investment'),
 ('Acct.Cash.Investment', 'o20250801_1', 'Initial Investment by member')]

## Test ledget Iterator

In [15]:
bk.df[bk.df.Acct.str.contains('Investment')]

,dt,amt,C2,CheckNo,desc,TransType,Acct,AcctSub,TDesc
1,12/29/2025,177.0,*,NaN,eDeposit in Branch 12/29/25 03:48:15 PM 14650 ...,Rev,Acct.Cash.Investment,o20250801_1,Initial Investment by member
52,08/20/2025,50.0,*,NaN,WFB OPENING DEPOSIT FROM CARD XXXXXXXXXXXX1980...,Rev,Acct.Cash.Investment,o20250801_1,Open Bank Acct Investment
53,08/20/2025,219000.0,*,NaN,WT FED#02M03 NATIONAL FINANCIAL /ORG=FRANCIS X...,Rev,Acct.Cash.Investment,o20250801_1,Initial Investment by member

In [11]:
# filter transactions X assets
import pandas as pd
aDF = llc.aObj.df
iDF = pd.merge(aDF, bk.df, 
         left_on=['dt','amt'], 
         right_on=['dt', 'amt'],
         how='inner')
iDF[['acct', 'amt', 'desc_x', 'AcctSub']]
bal = ('Balance_Acct.Cash')
iDF.loc[bal] = [llc.objName, float(iDF.amt.sum()),'LLC']
llcBalInvestment = iDF.amt.iloc[-1]
iDF

,acct,amt,desc_x,AcctSub
0,Acct.Cash.Investment,50.00,Open Bank Acct Investment,o20250801_1
1,Acct.Asset.Purchase,-213936.95,Purchase Property: 805 High Mesa,p20250826-805HMD
2,Acct.Cash.Investment,219000.00,Initial Investment by member,o20250801_1
3,Acct.Asset.Purchase,-177.00,Purchase Rental RV,p20251229-RV1
4,Acct.Cash.Investment,177.00,Initial Investment by member,o20250801_1

In [ ]:
bk.df