# LLC Object Editors

This notebook walks thru the financial workflow to update the general ledger (journal) and product periodic (monthly, YE) reports. 

Refer to [GHub> IRSGuides.ChartofAccounts.md](https://github.com/wbgroupmgr/LLC-WB-Group/blob/main/pages/IRSGuide/LLC-ChartOfAccoounts.md)

## Usage - refer to llcEditorCmd.py / ui.llcEditorCmd-UserGuide.md

In [1]:
# Load bookkeeping services : llc, coa, 
import os
from ledger.LLC import LLC
from pathlib import Path
import datetime
import pandas as pd
import numpy as np
from IPython.display import display, Markdown

from ledger.llcCOA import ChartOfAccounts
import pandas as pd



top = Path.cwd().parents[2]
llc = LLC('WBGroupLLC',debug=False, top=top)  # debug='details'
# Load Latest/YE Bank Stmt
llc._Bank()
# Chart of accounts
coa = ChartOfAccounts(llc)

<h2> Chart of Accounts

In [26]:
# Show COA for refernces
#coa.toDF()
coa.loadAll()['coaDict']

{'Acct.Cash.Bank': {'acctID': '1010',
  'acctDesc': '(Operating Bank Account: Cash )'},
 'Acct.Cash.Security': {'acctID': '1020',
  'acctDesc': 'Security Deposit Trust Account (Funds held for tenants; must be kept separate)'},
 'Acct.Fixed.Tangible.InConstruction': {'acctID': '1310',
  'acctDesc': 'Asset: Debit Buildings Not InService - purchase prices + construction Expenses'},
 'Acct.Fixed.Land': {'acctID': '1410', 'acctDesc': 'Land : value of land'},
 'Acct.Fixed.Tangible': {'acctID': '1420',
  'acctDesc': 'Buildings (The purchase price of the physical structure)'},
 'Acct.Fixed.Tangible.InService': {'acctID': '1430',
  'acctDesc': 'Building: Inservice value of building '},
 'Acct.Fixed.Depreciation.Accum': {'acctID': '1460',
  'acctDesc': 'Accumulated Depreciation (A "contra-asset" account tracking the building\'s value loss over time)'},
 'Acct.Fixed.Tangible.Improvements': {'acctID': '1470',
  'acctDesc': 'Buildings, Improvements (Major: new flooring, central A/C, complete remodels)'},
 'Acct.Liab.Payable': {'acctID': '2010',
  'acctDesc': 'Accounts Payable (Unpaid bills to vendors)'},
 'Acct.Liab.Morgage': {'acctID': '2100',
  'acctDesc': 'Mortgage Payable (The principal balance on your property loan)'},
 'Acct.Liab.Customer.Security': {'acctID': '2200',
  'acctDesc': 'Tenant Security Deposits Held (This offsets the cash in your trust account)'},
 'Acct.Liab.Customer.Rent.Prepai': {'acctID': '2300',
  'acctDesc': 'Prepaid Rent (Rent paid by tenants before it is due, first, last)'},
 'Acct.Equity.Owner.Capital.Funds': {'acctID': '3010',
  'acctDesc': 'Owner Contribution, Personal funds, taxable, increase Outside Basis)'},
 'Acct.Equity.Owner.Capital.Dist': {'acctID': '3020',
  'acctDesc': 'Owner Distribution, K1 Income, no change to outside basis.'},
 'Acct.Equity.Owner.Capital.Reinvestment': {'acctID': '3025',
  'acctDesc': 'Owner Contribution, tax-paid; increase Outside Basis'},
 'Acct.Equity.Earnings.PnL': {'acctID': '3100',
  'acctDesc': 'Retained Earnings (Cumulative profit or loss from previous years)'},
 'Acct.Rev.Rent': {'acctID': '4010', 'acctDesc': 'Rental Income'},
 'Acct.Rev.Fees.Late': {'acctID': '4020', 'acctDesc': 'Late Fee Income'},
 'Acct.Rev.Fee.Other': {'acctID': '4040',
  'acctDesc': 'Non-Refundable Fees (Pets, deposits)/Parking Fees'},
 'Acct.Rev.Services': {'acctID': '4030', 'acctDesc': 'Laundry/Vending Income'},
 'Acct.Rev.Util': {'acctID': '4050',
  'acctDesc': 'Utility Reimbursement (If tenants pay you back for shared utilities)'},
 'Acct.Exp.Adv': {'acctID': '5010', 'acctDesc': 'Advertising'},
 'Acct.Exp.Maint': {'acctID': '5020', 'acctDesc': 'Cleaning and Maintenance'},
 'Acct.Exp.Ins': {'acctID': '5030', 'acctDesc': 'Insurance'},
 'Acct.Exp.Fees.Legal': {'acctID': '5040',
  'acctDesc': 'Legal & Professional Fees (Accountants, lawyers)'},
 'Acct.Exp.Fees.Mgmt': {'acctID': '5050',
  'acctDesc': 'Management Fees (If using a third-party manager)'},
 'Acct.Exp.Operating': {'acctID': '5051',
  'acctDesc': 'Operating Exp, Subcriptions, HOA, etc.'},
 'Acct.Exp.Int.Morg': {'acctID': '5060',
  'acctDesc': 'Mortgage Interest (Interest only; principal goes to Liability 2100)'},
 'Acct.Exp.Repair': {'acctID': '5070',
  'acctDesc': 'Repairs (Routine fixes like leaky faucets)'},
 'Acct.Exp.Depreciation': {'acctID': '5075',
  'acctDesc': 'Depreciation Expense per period'},
 'Acct.Exp.Tax.Prop': {'acctID': '5080', 'acctDesc': 'Taxes (Property taxes)'},
 'Acct.Exp.Util': {'acctID': '5090',
  'acctDesc': 'Utilities (Water, trash, common area electric)'},
 'Acct.Exp.Other': {'acctID': '5099',
  'acctDesc': 'Misc - fallback if unknown)'},
 'Acct.Unrealized.Appreciation': {'acctID': '6010',
  'acctDesc': 'Unrealized Gains - appreciation'}}

In [3]:
# Test Initialize each LLC DB 

from ledger.llcAssets import llcAssets
aObj = llc.assets()

from ledger.llcExpRev import llcExpRev
erObj = llcExpRev(llc)
erObj.FN()

from ledger.llcFinancialReport import llcFinancialReport
frObj = llcFinancialReport(llc)
frObj.FN()

WARNING: No YR.2025.Beg.Cash in llcAsset DB,acct = Acct.Cash.Balance. -- default to 0.0

'/Users/frankrojas/GDrive/Family/Assets-Hobby/RealEstateInvestments/LLC-WB-Group/llcFinancialReport_WBGroupLLC.json'

In [4]:
# Tst functions
def TestWk(testNm, loadOpt=False):
    print()
    display(Markdown(f"{'_'*10} {testNm}"))

    display(Markdown("<h3> Init EditSession"))
    es = utilEditSession(llcName='WBGroupLLC', load = loadOpt)
    
    display(Markdown("<h4> Assert 0 recoreds in working, otherwise clean"))
    # Assert 0 working files
    display(es)
    
    display(Markdown("<h2>Test loadTemp w/ loadOpt = False"))
    es.loadTemp()
    
    display(Markdown("<h4> Assert 0 recoreds in working, no loads"))
    # load failse because loadOpt set to False
    display(es)

    return es

## Test utilWorkingDB for each DB

In [5]:
from util.utilEditSession import utilEditSession

_ = TestWk("\n<h2>1. Test init", loadOpt=False)
es = TestWk("\n<h2>2. Test Init w/ Load=True", loadOpt=True)
es.clean()

__________
<h2>1. Test init

<h3> Init EditSession

99 eSession bind objects: {'wkAssets': '/tmp/llcAssets_WBGroupLLC_temp.json', 'wkExpRev': '/tmp/llcExpRev_WBGroupLLC_temp.json'}

<h4> Assert 0 recoreds in working, otherwise clean

llcEditSession Status:
Work oID:wkAssets> num:13:13, st:NoChanges, Load:False,  edOpt:llc wFN:/tmp/llcAssets_WBGroupLLC_temp.json,
Work oID:wkExpRev> num:54:54, st:NoChanges, Load:False,  edOpt:llc wFN:/tmp/llcExpRev_WBGroupLLC_temp.json,

<h2>Test loadTemp w/ loadOpt = False

<h4> Assert 0 recoreds in working, no loads

llcEditSession Status:
Work oID:wkAssets> num:13:13, st:NoChanges, Load:False,  edOpt:llc wFN:/tmp/llcAssets_WBGroupLLC_temp.json,
Work oID:wkExpRev> num:54:54, st:NoChanges, Load:False,  edOpt:llc wFN:/tmp/llcExpRev_WBGroupLLC_temp.json,

__________
<h2>2. Test Init w/ Load=True

<h3> Init EditSession

99 eSession bind objects: {'wkAssets': '/tmp/llcAssets_WBGroupLLC_temp.json', 'wkExpRev': '/tmp/llcExpRev_WBGroupLLC_temp.json'}

<h4> Assert 0 recoreds in working, otherwise clean

llcEditSession Status:
Work oID:wkAssets> num:13:13, st:NoChanges, Load:True,  edOpt:llc wFN:/tmp/llcAssets_WBGroupLLC_temp.json,
Work oID:wkExpRev> num:54:54, st:NoChanges, Load:True,  edOpt:llc wFN:/tmp/llcExpRev_WBGroupLLC_temp.json,

<h2>Test loadTemp w/ loadOpt = False

<h4> Assert 0 recoreds in working, no loads

llcEditSession Status:
Work oID:wkAssets> num:13:13, st:NoChanges, Load:True,  edOpt:llc wFN:/tmp/llcAssets_WBGroupLLC_temp.json,
Work oID:wkExpRev> num:54:54, st:NoChanges, Load:True,  edOpt:llc wFN:/tmp/llcExpRev_WBGroupLLC_temp.json,

In [6]:
es

llcEditSession Status:
Work oID:wkAssets> num:0:13, st:NoChanges, Load:True,  edOpt:llc wFN:/tmp/llcAssets_WBGroupLLC_temp.json,
Work oID:wkExpRev> num:0:54, st:NoChanges, Load:True,  edOpt:llc wFN:/tmp/llcExpRev_WBGroupLLC_temp.json,

In [25]:
wk = es.oDict['llcExpRev']
wk.FN, wk.o.FN()

(<bound method utilWorkingDB.FN of Work oID:wkExpRev> num:54:54, st:NoChanges, Load:True,  edOpt:llc wFN:/tmp/llcExpRev_WBGroupLLC_temp.json,  >,
 '/Users/frankrojas/GDrive/Family/Assets-Hobby/RealEstateInvestments/LLC-WB-Group/pages/AccountingData/Accts/llcExpRev_WBGroupLLC.json')

In [24]:
#es.loadTemp()
import re

wk = es.oDict['llcExpRev']

def _delFld(d, fldList):
    for f in fldList:
        if f in d : del d['acctType']
    return d

wDF = pd.DataFrame(wk.load())


def toDesc(s):
    if pd.isna(s) : return s
        
    pat = r'ON \S* (.*)'
    m = re.search(pat, s)
    if m : 
        return(' '.join(m.group(1).split()[0:4]))
    else:
        return s

wDF.refDoc.apply(lambda s : toDesc(s))

0                                                   NaN
1                                                   NaN
2                     WITHDRAWAL MADE IN A BRANCH/STORE
3                   AMAZON MKTPL*6Y5UJ Amzn.com/bill WA
4     Pedernales Elect TEL PMTS 082825 1SNKYQ W B GR...
5                                           CHECK # 101
6                               Kings Feed And Hardware
7                   AMAZON MKTPL*B108S Amzn.com/bill WA
8             MOBILE DEPOSIT : REF NUMBER :409290718471
9                   AMAZON MKTPL*NJ7XX Amzn.com/bill WA
10                           WIMBERLEY ACE WIMBERLEY TX
11                            WAL-MART #0404 SAN MARCOS
12                                          CHECK # 102
13                        LOWES #00907* 866-483-7521 NC
14                           WIMBERLEY ACE WIMBERLEY TX
15                               LOWE'S #159 SAN MARCOS
16                             LOWES #00159* SAN MARCOS
17                           WIMBERLEY ACE WIMBERLEY TX
18                              H-E-B #708 WIMBERLEY TX
19                           WIMBERLEY ACE WIMBERLEY TX
20                           WIMBERLEY ACE WIMBERLEY TX
21                           WIMBERLEY ACE WIMBERLEY TX
22                           WIMBERLEY ACE WIMBERLEY TX
23    BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...
24                       TEXAS DISPOSAL SYS 800-3758375
25                           WIMBERLEY ACE WIMBERLEY TX
26                              H-E-B #708 WIMBERLEY TX
27                  AMAZON MKTPL*NM32N Amzn.com/bill WA
28                               Harbor Freight Tools U
29                                   SQ *RODCO STEEL DI
30          BILL PAY Water-COMWSC RECURRING 38 ON 10-20
31                           WIMBERLEY ACE WIMBERLEY TX
32    VENMO ADDFUNDS 251022 1045679339909 FRANCIS ROJAS
33                                                  NaN
34                                      Promotion Bonus
35    TRUIST ACCTVERIFY 251024 15280212827 ALEJANDRO...
36    TRUIST ACCTVERIFY 251024 15280212821 ALEJANDRO...
37    TRUIST ACCTVERIFY 251024 15280212831 ALEJANDRO...
38                      LAIRD PLASTICS SAN 469-299-7029
39                  AMAZON MKTPL*NK5PS Amzn.com/bill WA
40                     SP GROWERS SOLUTIO GROWERSSOLUTI
41    BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...
42                                   REF # BBT348258735
43                     SP GROWERS SOLUTIO GROWERSSOLUTI
44                  AMAZON MKTPL*B80W8 Amzn.com/bill WA
45                                    HAYS CO TX WIMBER
46                                    HAYS CO TX WIMBER
47          BILL PAY Water-COMWSC RECURRING 38 ON 11-18
48                                   REF # BBT352817659
49    BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...
50          BILL PAY Water-COMWSC RECURRING 38 ON 12-18
51    ALLSTATE IND CO INS PYMT DEC024 00000043853221...
52    eDeposit in Branch 12/29/25 03:48:15 PM 14650 ...
53    Cash eWithdrawal in Branch 12/29/2025 13:47 PM...
Name: refDoc, dtype: object

In [46]:
for wkID, wk  in es.oDict.items():
    display(Markdown(f"<h2> Test Wk.Load - {wkID}"))
    
    wkDF = pd.DataFrame(wk.load())
    display(Markdown(f"<h2> Test {wk.oID} Load"))
    display(wkDF.head(3))
    print("\n-----------\n")
    oDF = pd.DataFrame(wk.o.load())
    display(Markdown(f"<h2> Test {wk.o.oID} Load"))
    display(oDF.head(3))

<h2> Test Wk.Load - wkAssets

<h2> Test wkAssets Load

,dt,desc,amt,aType,acct,Ledger,acctMajor,acctMinor,acctSub,propNm,propID,propAddr,propOwners,tID,tDB,refDB,refDoc,_unknown,acctType
0,2025.08.20,YR.2025.Begining Balance: Cash,0.0,Debit,Acct.Cash.Bank,Acct.Equity.Earnings.PnL,None,None,None,Cash_LLC,a20250820-Cash1,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250820-Cash1,llcAssets,llcBank,Cash_LLC:llcBank Stmt,{},Other
1,2025.08.20,Initial Investment by member,219000.0,Debit,Acct.Cash.Bank,Acct.Equity.Owner.Cash,,,,H_805HighMesa,e20250826-805HMD,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250826-Cash1,llcAssets,llcAssets,H_805HighMesa: Closing Docs 2025.08.26,{},Other
2,2025.08.20,Open Bank Acct Investment,50.0,Debit,Acct.Cash.Bank,Acct.Equity.Owner.Cash,,,ClosingCosts,H_805HighMesa,e20250826-805HMD,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250826-Cash2,llcAssets,llcAssets,H_805HighMesa: Closing Docs 2025.08.26,{},Other

-----------

<h2> Test llcAssets Load

,dt,desc,amt,aType,acct,Ledger,acctMajor,acctMinor,acctSub,propNm,propID,propAddr,propOwners,tID,tDB,refDB,refDoc,_unknown
0,2025.08.20,YR.2025.Begining Balance: Cash,0.0,Debit,Acct.Cash.Bank,Acct.Equity.Earnings.PnL,NaN,NaN,NaN,Cash_LLC,a20250820-Cash1,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250820-Cash1,llcAssets,llcBank,Cash_LLC:llcBank Stmt,{}
1,2025.08.20,Initial Investment by member,219000.0,Debit,Acct.Cash.Bank,Acct.Equity.Owner.Cash,NaN,NaN,NaN,H_805HighMesa,e20250826-805HMD,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250826-Cash1,llcAssets,llcAssets,H_805HighMesa: Closing Docs 2025.08.26,{}
2,2025.08.20,Open Bank Acct Investment,50.0,Debit,Acct.Cash.Bank,Acct.Equity.Owner.Cash,NaN,NaN,NaN,H_805HighMesa,e20250826-805HMD,"177 Kingsway Dr, Wimberley, 786767",{'o20250801_1': 100},a20250826-Cash2,llcAssets,llcAssets,H_805HighMesa: Closing Docs 2025.08.26,{}

<h2> Test Wk.Load - wkExpRev

<h2> Test wkExpRev Load

,dt,amt,aType,acct,acctType,Ledger,desc,acctSub,propNm,propID,propAddr,propOwners,tID,tDB,refDB,refDoc,_unknown,acctMajor,acctMinor
0,2025.08.20,219000.00,Debit,Acct.Cash.Bank,Other,Acct.Equity.Owner.Cash,Owner investment,,H_805HighMesa,,,,2025.08.20_219000.0,llcBank,llcBank,WT FED#02M03 NATIONAL FINANCIAL /ORG=FRANCIS X...,{},NaN,NaN
1,2025.08.20,50.00,Debit,Acct.Cash.Bank,Other,Acct.Equity.Owner.Cash,Owner Investment,None,H_805HighMesa,None,None,None,2025.08.20_50.0,llcBank,llcBank,WFB OPENING DEPOSIT FROM CARD XXXXXXXXXXXX1980...,{},NaN,NaN
2,2025.08.26,213936.95,Credit,Acct.Cash.Bank,Other,Acct.Fixed.Tangible.InService,Property Purchase,None,H_805HighMesa,None,None,None,2025.08.26_213936.95,llcBank,llcBank,WITHDRAWAL MADE IN A BRANCH/STORE,{},NaN,NaN

-----------

<h2> Test llcExpRev Load

,dt,desc,amt,aType,acct,Ledger,acctMajor,acctMinor,acctSub,propNm,propID,propAddr,propOwners,tID,tDB,refDB,refDoc,_unknown
0,2025.08.20,Owner investment,219000.00,Debit,Acct.Cash.Bank,Acct.Equity.Owner.Cash,NaN,NaN,NaN,H_805HighMesa,NaN,NaN,NaN,2025.08.20_219000.0,llcBank,llcBank,WT FED#02M03 NATIONAL FINANCIAL /ORG=FRANCIS X...,{}
1,2025.08.20,Owner Investment,50.00,Debit,Acct.Cash.Bank,Acct.Equity.Owner.Cash,NaN,NaN,NaN,H_805HighMesa,NaN,NaN,NaN,2025.08.20_50.0,llcBank,llcBank,WFB OPENING DEPOSIT FROM CARD XXXXXXXXXXXX1980...,{}
2,2025.08.26,Property Purchase,213936.95,Credit,Acct.Cash.Bank,Acct.Fixed.Tangible.InService,NaN,NaN,NaN,H_805HighMesa,NaN,NaN,NaN,2025.08.26_213936.95,llcBank,llcBank,WITHDRAWAL MADE IN A BRANCH/STORE,{}

In [ ]:
stop

In [9]:
es.clean()

wkAssets Warning: Remove failed on Working file (/tmp/llcAssets_WBGroupLLC_temp.json) - error:[Errno 2] No such file or directory: '/tmp/llcAssets_WBGroupLLC_temp.json'
wkExpRev Warning: Remove failed on Working file (/tmp/llcExpRev_WBGroupLLC_temp.json) - error:[Errno 2] No such file or directory: '/tmp/llcExpRev_WBGroupLLC_temp.json'

## Load Temp files for Editors

In [ ]:
  # Load Notebook Editor
from util.uiEditors import TransactionEditor
from ledger.llcExpRev import llcExpRev

from util.uiEditors import nbAssetEditor, nbExpenseEditor

aObj = llc.assets()
erObj = llcExpRev(llc)

aEd = nbAssetEditor(aObj)
erEd = nbExpenseEditor(erObj)

aList = aObj.load()
aEd.saveTemp(aList)

erList = erObj.load()
erEd.saveTemp(erList)
print(f"Asset: {len(aList)} at FN:{aEd.oFN}")
print(f"ExpRev {len(erList)} at FN:{erEd.oFN}")

## Start Editor - both | assets | exprev

In [ ]:
edOpt = 'assets'
if edOpt == 'both':
    ed = TransactionEditor(
        asset_file=aEd.oFN,
        exprev_file=erEd.oFN
    )
    # Start the editor with debug mode
    
elif edOpt == 'assets':
    ed = TransactionEditor(asset_file=aEd.oFN)
elif edOpt == 'exprev':
    ed = TransactionEditor(exprev_file=erEd.oFN)

ed.start(debug=True) #port=5000, height=800, debug=True)

In [ ]:
aObj.load()

In [ ]:
ed = nbAssetEditor(llc.assets())
editMaster = True
if editMaster:
    # Edit Master llcAsset DB ------ move master into temp
    mList = ed.o.load() #len(aList)
    ed.saveTemp(mList)
    ed.editTemp()
else:
    # Temp has not been saved
    ed.editTemp()

## Start Asset Editor

In [ ]:
# Load Notebook Editor
from util.uiEditors import nbAssetEditor

ed = nbAssetEditor(llc.assets())
editMaster = True
if editMaster:
    # Edit Master llcAsset DB ------ move master into temp
    mList = ed.o.load() #len(aList)
    ed.saveTemp(mList)
    ed.editTemp()
else:
    # Temp has not been saved
    ed.editTemp()

In [ ]:
stop

In [ ]:
ed.stop()

In [ ]:
if True:
    # Manually update Master w/ temp
    # Do this once reconcilation is done
    mList = ed.loadTemp()
    ed.o.save(mList)

In [ ]:
ed.o.FN()

In [ ]:
ed.stop()