In [1]:
# Load bookkeeping services
import os
from ledger.LLC import LLC
from pathlib import Path
import datetime
import pandas as pd
import numpy as np
from IPython.display import display, Markdown

top = os.path.join(Path.home(), 'GDrive/Family/Assets-Hobby/RealEstateInvestments/LLC-WB-Group')
llc = LLC('WBGroupLLC',debug=False, top=top)  # debug='details'

In [2]:
llc._Bank()
llc.bk.df

,dt,amt,C2,CheckNo,desc,TransType,Acct,AcctSub,TDesc
0,2025.12.29,-177.00,*,NaN,Cash eWithdrawal in Branch 12/29/2025 13:47 PM...,Exp,Acct.Exp.Misc,Misc,Misc Expense
1,2025.12.29,177.00,*,NaN,eDeposit in Branch 12/29/25 03:48:15 PM 14650 ...,Rev,Acct.Cash.Misc,Misc,Misc Income
2,2025.12.26,-135.80,*,NaN,ALLSTATE IND CO INS PYMT DEC024 00000043853221...,Exp,Acct.Exp.Util,Ins_Home,Pay Monthly Util
3,2025.12.18,-50.00,*,NaN,BILL PAY Water-COMWSC RECURRING 38 ON 12-18,Exp,Acct.Exp.Util,Water,Pay Monthly Util
4,2025.12.10,-129.16,*,NaN,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,Exp,Acct.Exp.Util,Elec,Pay Monthly Util
5,2025.12.01,1500.00,*,NaN,ZELLE FROM NICOLA ROJAS ON 12/01 REF # BBT3528...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
6,2025.11.18,-50.00,*,NaN,BILL PAY Water-COMWSC RECURRING 38 ON 11-18,Exp,Acct.Exp.Util,Water,Pay Monthly Util
7,2025.11.17,-2.00,*,NaN,PURCHASE AUTHORIZED ON 11/15 HAYS CO TX WIMBER...,Exp,Acct.Exp.Misc,hays,Expense: 11/15 hays co tx wimber fort worth tx...
8,2025.11.17,-30.00,*,NaN,PURCHASE AUTHORIZED ON 11/15 HAYS CO TX WIMBER...,Exp,Acct.Exp.Misc,hays,Expense: 11/15 hays co tx wimber san marcos tx...
9,2025.11.17,-19.47,*,NaN,PURCHASE AUTHORIZED ON 11/15 AMAZON MKTPL*B80W...,Exp,Acct.Exp.Misc,amazon,Expense: 11/15 amazon mktpl*b80w8 amzn.com/bil...
10,2025.11.17,-32.42,*,NaN,PURCHASE AUTHORIZED ON 11/14 SP GROWERS SOLUTI...,Exp,Acct.Exp.Misc,sp,Expense: 11/14 sp growers solutio growerssolut...
11,2025.11.12,1500.00,*,NaN,ZELLE FROM NICOLA ROJAS ON 11/11 REF # BBT3482...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
12,2025.11.10,-119.49,*,NaN,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,Exp,Acct.Exp.Util,Elec,Pay Monthly Util
13,2025.11.07,-42.15,*,NaN,PURCHASE AUTHORIZED ON 11/06 SP GROWERS SOLUTI...,Exp,Acct.Exp.Misc,sp,Expense: 11/06 sp growers solutio growerssolut...
14,2025.11.03,-73.56,*,NaN,PURCHASE AUTHORIZED ON 11/02 AMAZON MKTPL*NK5P...,Exp,Acct.Exp.Misc,amazon,Expense: 11/02 amazon mktpl*nk5ps amzn.com/bil...
15,2025.11.03,-487.13,*,NaN,PURCHASE AUTHORIZED ON 10/31 LAIRD PLASTICS SA...,Exp,Acct.Exp.Misc,laird,Expense: 10/31 laird plastics san 469-299-7029...
16,2025.10.24,-0.53,*,NaN,TRUIST ACCTVERIFY 251024 15280212831 ALEJANDRO...,Exp,Acct.Exp.Misc,Misc,Misc Expense
17,2025.10.24,0.29,*,NaN,TRUIST ACCTVERIFY 251024 15280212821 ALEJANDRO...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
18,2025.10.24,0.24,*,NaN,TRUIST ACCTVERIFY 251024 15280212827 ALEJANDRO...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
19,2025.10.24,400.00,*,NaN,Promotion Bonus,Rev,Acct.Rev.Other,Bank,Bank Promotion for account openning
20,2025.10.23,1000.00,*,NaN,ZELLE FROM ALEJANDRO VILLARREAL ON 10/23 REF #...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
21,2025.10.22,-135.00,*,NaN,VENMO ADDFUNDS 251022 1045679339909 FRANCIS ROJAS,Exp,Acct.Exp.Maint,Maintenance,"Repair Utility Outlet,Electrician"
22,2025.10.22,-36.09,*,NaN,PURCHASE AUTHORIZED ON 10/22 WIMBERLEY ACE WIM...,Exp,Acct.Exp.Misc,wimberley,Expense: 10/22 wimberley ace wimberley tx p000...
23,2025.10.20,-50.00,*,NaN,BILL PAY Water-COMWSC RECURRING 38 ON 10-20,Exp,Acct.Exp.Util,Water,Pay Monthly Util
24,2025.10.17,-57.31,*,NaN,PURCHASE AUTHORIZED ON 10/16 SQ *RODCO STEEL D...,Exp,Acct.Exp.Misc,sq,Expense: 10/16 sq *rodco steel di new braunfel...
25,2025.10.16,-60.58,*,NaN,PURCHASE AUTHORIZED ON 10/16 Harbor Freight To...,Exp,Acct.Exp.Misc,harbor,Expense: 10/16 harbor freight tools u san marc...
26,2025.10.14,-19.47,*,NaN,PURCHASE AUTHORIZED ON 10/13 AMAZON MKTPL*NM32...,Exp,Acct.Exp.Misc,amazon,Expense: 10/13 amazon mktpl*nm32n amzn.com/bil...
27,2025.10.14,-90.90,*,NaN,PURCHASE AUTHORIZED ON 10/13 TEXAS DISPOSAL SY...,Exp,Acct.Exp.Misc,texas,Expense: 10/13 texas disposal sys 800-3758375 ...
28,2025.10.14,-108.32,*,NaN,PURCHASE AUTHORIZED ON 10/12 H-E-B #708 WIMBER...,Exp,Acct.Exp.Misc,h-e-b,Expense: 10/12 h-e-b #708 wimberley tx s465285...
29,2025.10.14,-30.71,*,NaN,PURCHASE AUTHORIZED ON 10/10 WIMBERLEY ACE WIM...,Exp,Acct.Exp.Misc,wimberley,Expense: 10/10 wimberley ace wimberley tx s385...
30,2025.10.10,-72.50,*,NaN,BUSINESS TO BUSINESS ACH Pedernales_Elec ELEC_...,Exp,Acct.Exp.Util,Elec,Pay Monthly Util
31,2025.10.09,-37.87,*,NaN,PURCHASE AUTHORIZED ON 10/08 WIMBERLEY ACE WIM...,Exp,Acct.Exp.Misc,wimberley,Expense: 10/08 wimberley ace wimberley tx s465...
32,2025.10.09,-14.06,*,NaN,PURCHASE AUTHORIZED ON 10/08 WIMBERLEY ACE WIM...,Exp,Acct.Exp.Misc,wimberley,Expense: 10/08 wimberley ace wimberley tx s585...
33,2025.10.09,14.06,*,NaN,PURCHASE RETURN AUTHORIZED ON 10/08 WIMBERLEY ...,Rev,Acct.Exp.Misc,wimberley,Expense: 10/08 wimberley ace wimberley tx s465...
34,2025.10.08,-34.63,*,NaN,PURCHASE AUTHORIZED ON 10/07 WIMBERLEY ACE WIM...,Exp,Acct.Exp.Misc,wimberley,Expense: 10/07 wimberley ace wimberley tx s585...
35,2025.10.08,-65.36,*,NaN,PURCHASE AUTHORIZED ON 10/07 H-E-B #708 WIMBER...,Exp,Acct.Exp.Misc,h-e-b,Expense: 10/07 h-e-b #708 wimberley tx s345280...
36,2025.10.08,-51.06,*,NaN,PURCHASE AUTHORIZED ON 10/07 WIMBERLEY ACE WIM...,Exp,Acct.Exp.Misc,wimberley,Expense: 10/07 wimberley ace wimberley tx s345...
37,2025.10.08,27.04,*,NaN,PURCHASE RETURN AUTHORIZED ON 10/07 LOWES #001...,Rev,Acct.Exp.Misc,lowes,Expense: 10/07 lowes #00159* san marcos tx s34...
38,2025.10.07,-50.00,*,102.0,CHECK # 102,Exp,Acct.Exp.Util,Util,Pay Electrician Repair Outlet
39,2025.10.07,-27.04,*,NaN,PURCHASE AUTHORIZED ON 10/07 LOWE'S #159 SAN M...,Exp,Acct.Exp.Misc,lowe's,Expense: 10/07 lowe's #159 san marcos tx p3052...
40,2025.10.07,-14.06,*,NaN,PURCHASE AUTHORIZED ON 10/07 WIMBERLEY ACE WIM...,Exp,Acct.Exp.Misc,wimberley,Expense: 10/07 wimberley ace wimberley tx p000...
41,2025.10.07,-31.86,*,NaN,PURCHASE AUTHORIZED ON 10/06 LOWES #00907* 866...,Exp,Acct.Exp.Misc,lowes,Expense: 10/06 lowes #00907* 866-483-7521 nc s...
42,2025.10.06,-140.73,*,NaN,PURCHASE AUTHORIZED ON 10/04 WAL-MART #0404 SA...,Exp,Acct.Exp.Misc,wal-mart,Expense: 10/04 wal-mart #0404 san marcos tx p0...
43,2025.10.03,-17.31,*,NaN,PURCHASE AUTHORIZED ON 10/03 WIMBERLEY ACE WIM...,Exp,Acct.Exp.Misc,wimberley,Expense: 10/03 wimberley ace wimberley tx p000...
44,2025.10.03,-8.29,*,NaN,PURCHASE AUTHORIZED ON 10/01 AMAZON MKTPL*NJ7X...,Exp,Acct.Exp.Misc,amazon,Expense: 10/01 amazon mktpl*nj7xx amzn.com/bil...
45,2025.09.29,30.00,*,NaN,MOBILE DEPOSIT : REF NUMBER :409290718471,Rev,Acct.Cash.Misc,Misc,Misc Income
46,2025.09.22,-38.94,*,NaN,PURCHASE AUTHORIZED ON 09/19 AMAZON MKTPL*B108...,Exp,Acct.Exp.Misc,amazon,Expense: 09/19 amazon mktpl*b108s amzn.com/bil...
47,2025.09.10,-25.94,*,NaN,PURCHASE AUTHORIZED ON 09/10 Kings Feed And Ha...,Exp,Acct.Exp.Misc,kings,Expense: 09/10 kings feed and hardware wimberl...
48,2025.09.03,-150.00,*,101.0,CHECK # 101,Exp,Acct.Exp.Util,Water,Pay Monthly Util
49,2025.08.28,-250.00,*,NaN,Pedernales Elect TEL PMTS 082825 1SNKYQ W B GR...,Exp,Acct.Exp.Util,Elec,Pay Monthly Util
50,2025.08.28,-75.76,*,NaN,PURCHASE AUTHORIZED ON 08/27 AMAZON MKTPL*6Y5U...,Exp,Acct.Exp.Misc,amazon,Expense: 08/27 amazon mktpl*6y5uj amzn.com/bil...
51,2025.08.26,-213936.95,*,NaN,WITHDRAWAL MADE IN A BRANCH/STORE,Exp,Acct.Exp.Misc,Misc,Misc Expense
52,2025.08.20,50.00,*,NaN,WFB OPENING DEPOSIT FROM CARD XXXXXXXXXXXX1980...,Rev,Acct.Cash.Misc,Misc,Misc Income
53,2025.08.20,219000.00,*,NaN,WT FED#02M03 NATIONAL FINANCIAL /ORG=FRANCIS X...,Rev,Acct.Cash.Misc,Misc,Misc Income

In [5]:
for a  in llc.bk.df.Acct.unique():
    if coa.get(a) is None:
        pass

ChartOfAccounts ERROR: acct:Acct.Cash.Misc was not found in ChartOfAccounts DB
ChartOfAccounts ERROR: acct:Acct.Cash.Income was not found in ChartOfAccounts DB

In [7]:
df = llc.bk.df
df[df.Acct == 'Acct.Cash.Income']

,dt,amt,C2,CheckNo,desc,TransType,Acct,AcctSub,TDesc
5,2025.12.01,1500.00,*,NaN,ZELLE FROM NICOLA ROJAS ON 12/01 REF # BBT3528...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
11,2025.11.12,1500.00,*,NaN,ZELLE FROM NICOLA ROJAS ON 11/11 REF # BBT3482...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
17,2025.10.24,0.29,*,NaN,TRUIST ACCTVERIFY 251024 15280212821 ALEJANDRO...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
18,2025.10.24,0.24,*,NaN,TRUIST ACCTVERIFY 251024 15280212827 ALEJANDRO...,Rev,Acct.Cash.Income,c20251001-1,Rental Income
20,2025.10.23,1000.00,*,NaN,ZELLE FROM ALEJANDRO VILLARREAL ON 10/23 REF #...,Rev,Acct.Cash.Income,c20251001-1,Rental Income

## CHart of Accounts

In [4]:
from ledger.llcCOA import ChartOfAccounts
import pandas as pd
coa = ChartOfAccounts(llc)

# List 
df = pd.DataFrame(coa.load()).transpose()
df.acctCat.unique()
df

,acctCat,acctSub,acctID,aacctDesc
Acct.Cash.Bank,Acct.Cash,Bank,1010,Cash in Bank (Operating Account)
Acct.Cash.Security,Acct.Cash,Security,1020,1 Security Deposit Trust Account (Funds held f...
Acct.Fixed.Tangible.InConstuction,Acct.Fixed,Tangible.InConstruction,1310,Asset: Debit Buildings Not InService - purchas...
Acct.Fixed.Land,Acct.Fixed,Land,1410,Land
Acct.Fixed.Tangible,Acct.Fixed,Tangible,1420,Buildings (The purchase price of the physical ...
Acct.Fixed.Tangible.InService,Acct.Fixed,Tangible.InService,1430,Buildings InService (The purchase price of the...
Acct.Fixed.Depreciation.Accum,Acct.Fixed,Depreciation.Accum,1460,"Accumulated Depreciation (A ""contra-asset"" acc..."
Acct.Liab.Payable,Acct.Liab,Payable,2010,Accounts Payable (Unpaid bills to vendors)
Acct.Liab.Morgage,Acct.Liab,Morgage,2100,Mortgage Payable (The principal balance on you...
Acct.Liab.Customer.Security,Acct.Liab,Customer.Security,2200,Tenant Security Deposits Held (This offsets th...
Acct.Liab.Customer.Rent.Prepai,Acct.Liab,Customer.Rent.Prepai,2300,Prepaid Rent (Rent paid by tenants before it i...
Acct.Equity.Owner.Cash,Acct.Equity,Owner.Cash,3010,Owner’s Contribution (Personal funds you put i...
Acct.Equity.Owner.Dist,Acct.Equity,Owner.Dist,3020,Owner’s Distribution (Money you take out of th...
Acct.Equity.Owner.Draw,Acct.Equity,Owner.Draw,3025,Owner’s Draw (Money you take out of the business)
Acct.Equity.Earnings.PnL,Acct.Equity,Earnings.PnL,3100,Retained Earnings (Cumulative profit or loss f...
Acct.Rev.OwnerRent,Acct.Rev,OwnerRent,4010,Rental Income
Acct.Rev.OwnerFees,Acct.Rev,OwnerFees,4020,Late Fee Income
Acct.Rev.Services,Acct.Rev,Services,4030,Laundry/Vending Income
Acct.Rev.Other,Acct.Rev,Other,4040,Pet Fees/Parking Fees
Acct.Rev.Util,Acct.Rev,Util,4050,Utility Reimbursement (If tenants pay you back...
Acct.Exp.Adv,Acct.Exp,Adv,5010,Advertising
Acct.Exp.Maint,Acct.Exp,Maint,5020,Cleaning and Maintenance
Acct.Exp.Ins,Acct.Exp,Ins,5030,Insurance
Acct.Exp.Fees.Legal,Acct.Exp,Fees.Legal,5040,"Legal & Professional Fees (Accountants, lawyers)"
Acct.Exp.Fees.Mgmt,Acct.Exp,Fees.Mgmt,5050,Management Fees (If using a third-party manager)
Acct.Exp.Int.Morg,Acct.Exp,Int.Morg,5060,Mortgage Interest (Interest only; principal go...
Acct.Exp.Repair,Acct.Exp,Repair,5070,Repairs (Routine fixes like leaky faucets)
Acct.Exp.Tax.Prop,Acct.Exp,Tax.Prop,5080,Taxes (Property taxes)
Acct.Exp.Util,Acct.Exp,Util,5090,"Utilities (Water, trash, common area electric)"
Acct.Exp.Misc,Acct.Exp,Other,5099,Misc - fallback if unknown)

In [ ]:
# Load Notebook Editor
from util.uiEditors import nbAssetEditor

ed = nbAssetEditor(llc.assets())
ed.o #len(aList)
aList = ed.loadTemp()
ed.editTemp()

In [ ]:
import json
#with open(coa.FN(), 'w') as fio:
#    json.dump(aDict, fio, indent=4)

In [ ]:
ed.o.FN()

In [ ]:
# Asset EDITOR WORKFLOW

In [ ]:
import pandas as pd
df = pd.DataFrame(llc.assets().load())

In [ ]:
sDF = df.groupby(['acct', 'aType']).amt.sum().unstack()
sDF.loc['Total'] = sDF.sum(axis=0)
sDF['diff'] = sDF.sum(axis=1)
sDF